title: Lee Janzen
subtitle: Junior Software Engineer and Technical Manager
description: >- # this means to ignore newlines until "baseurl:"
    Lee Janzen is a builder, leader, and force of curiosity. They are new to software engineering and passionate about data driven projects.

url: "https://leejanzen91.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: Home
      url: /
    - text: Portfolio
      url: /portfolio
   # - text: Blog
  #    url: /blog
   # - text: Gallery
   #   url: /gallery
   # - text: Shop
  #    url : /shop
    - text: Contact
      url : /contact


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile.jpg
author: Lee Janzen
author_bio: Lee Janzen is a builder, leader, and force of curiosity. They are new to software engineering and passionate about data driven projects.
author_email: "leejanzen91@gmail.com"
author_location: Seattle, WA
author_website_url: "https://sujaykundu.com"
typewrite-text: Forge your own path

# Experiences
author_work_experiences:
              company_name: Bellevue College
              company_logo: BClogo.jpg
              company_url: https://www.bellevuecollege.edu/
              designation: Trio Tutor
              description: Math and Programming tutor for first-generation college students. Educated others in offbeat ways to give multiple new perspectives, which improved understanding and performance for students.
              visibility: true
              company_name: Lee Janzen Co.
              company_logo: logosewn.png
              company_url: https://microsoft.com
              designation: Owner & Freelancer
              description: Researched innovative business management and advertising solutions. Created unique code for small personal software projects. Experienced artist that designs individual works based on customer feedback, combinging code with fashion to make one of a kind commisoned cosplays for clients.
              visibility: true
              company_name: Greenclean
              company_logo: greenclean.jpg
              company_url: https://www.facebook.com/greencleancoloradosprings
              designation: General Manager
              description: Grew locally owned, eco-friendly maid company from 5 clients to 300+.Triaged and resolved customer conflicts while managing small business. Experienced at lead generation, network marketing, and pitching product. Practiced with Emotional Intelligence for navigating workplace relationships with employees, colleagues, and upper management. Sold client list for owner profit at end of start up phase out.
              visibility: true
              company_name: King Soopers
              company_logo: KSlogo.png
              company_url: https://www.kingsoopers.com/
              designation: Assistent Deli Manager
              description: Worked up from grocery bagging position to 3 years of management, where I recieved management training through kroger's leadership program. Managed teams of up to 25 employees, working alongside team members to accomplish targeted goals. Developed excellent communication skills to keep team solution-focused and detail-oriented. Addressed team management problems with confidence and assertiveness. Hit projected targets on schedule & within budget, while maintaining employee advancement. Proposed original solutions to a problem that saved my company thousands a year.
              visibility: true

# Education
author_education_details:
                college_logo: UWlogo.jpg
                college_name: Univeristy of Washington - Seattle
                college_url: https://www.cs.washington.edu/
                college_degree: CS with Data Science Minor
                description: B.S. - Graduation expected June 2023
                visibility: true
                college_logo: BClogo.jpg
                college_name: Bellevue College
                college_url: https://www.bellevuecollege.edu/
                college_degree: General Transfer
                description: A.A.S. - June 2021 - GPA 3.93
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: true
              - project_thumbnail: hack4r.PNG
                project_title: Hack4r
                project_description: A Platform built for Hackers and Penetration Testers
                project_url: https://hack4r.com
                visibility: true

# social links
#twitter_username: johndoe
github_username:  leejanzen91
#facebook_username: johndoe
linkedin_username: leejanzen91
#behance_username: johndoe
#instagram_username: leejanzen91
#medium_username: johndoe
#telegram_username: johndoe
#dribbble_username: johndoe
#flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
#hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: leejanzen91

# mailchimp embedded form url (newsletter):
#mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# contact form - (choose formspress or getform)
getform_endpoint: 1de06dc7-823e-409c-ad7b-8ab359b6d6b7
#formspree_email: johndoe@gmail.com

# releases - widget can be (sidebar, modal or embed)
#olvy_organization: devlopr
#olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: false

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: false
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
